### ISSUE TITLE
Trade tariff was handed over to HMRC

### ISSUE THREAD

**Issue by matthewford** [x-govuk/govuk-services#410]
The source code for the trade tariff is now managed by HMRC.

https://github.com/trade-tariff/trade-tariff-backend

https://govuk-digital-services.herokuapp.com/projects/trade-tariff

**Comment by frankieroberto** [comment]
@matthewford thanks for reporting this! Fixed in #421. I also updated the service name, although I'm not 100% sure what the best name for the service is, as it's named slightly different on the start page, the service header, and in the `<h1>` of the service.
